### ISSUE TITLE
Add to stackage?

### ISSUE THREAD

**Issue by dbaynard** [christian-marie/time-qq#3]
Hi @christian-marie,

I'm hoping to upload a package which depends on this to stackage. If I just add my package, this will be added implicitly, but it's better to be explicit. Would you add it, or if not would you object to me adding it explicitly?

**Comment by christian-marie** [comment]
I use nix so have no motive to add it, I'm happy for you to do so.
Let me know if there's anything you need.

**Comment by christian-marie** [comment]
Oh and thanks, if you do.

**Comment by dbaynard** [comment]
This is in progress — thanks, @christian-marie. I'll ping you if I get a message about relaxing version bounds, etc.
